import {
  ShopSettings,
  User,
  Customer,
  MeasurementProfile,
  ProductOrService,
  InventoryItem,
  StaffMember,
  AttendanceRecord,
  PerformanceRecord,
  SalaryPayout,
  Sale,
  Invoice,
  AuditEvent,
} from '../types';

export const INITIAL_SHOP_SETTINGS: ShopSettings = {
  shopName: 'Al-Mamlaka Haute Couture & Tailoring',
  arabicShopName: 'المملكة للخياطة الراقية',
  crNumber: 'CR-104829-BH',
  vatNumber: '300092817400003',
  phone: '+973 1729 4488',
  address: 'Building 402, Road 2808, Block 328, Manama Souq, Kingdom of Bahrain',
  receiptFooter: 'Thank you for choosing Al-Mamlaka! Fitting guaranteed within 7 days.',
  invoiceTerms: 'Payment due upon receipt or completion of tailoring order. Terms subject to Bahrain commercial law.',
  currency: 'BHD',
};

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'Tariq Al-Mansoor',
    login: 'tariq.admin',
    role: 'admin',
    status: 'active',
    createdAt: '2026-01-10T08:00:00Z',
    lastLogin: '2026-08-13T09:00:00Z',
  },
  {
    id: 'usr-2',
    name: 'Yousef Hassan',
    login: 'yousef.pos',
    role: 'sales',
    status: 'active',
    createdAt: '2026-01-15T09:30:00Z',
    lastLogin: '2026-08-13T08:45:00Z',
  },
  {
    id: 'usr-3',
    name: 'Rashid Khan (Master Tailor)',
    login: 'rashid.tailor',
    role: 'tailor',
    status: 'active',
    createdAt: '2026-02-01T10:00:00Z',
    lastLogin: '2026-08-12T17:30:00Z',
  },
  {
    id: 'usr-4',
    name: 'Bilal Ahmad (Store Manager)',
    login: 'bilal.inventory',
    role: 'inventory',
    status: 'active',
    createdAt: '2026-02-10T11:00:00Z',
    lastLogin: '2026-08-13T07:15:00Z',
  },
  {
    id: 'usr-5',
    name: 'Fatima Al-Baharna',
    login: 'fatima.payroll',
    role: 'payroll',
    status: 'active',
    createdAt: '2026-03-01T09:00:00Z',
    lastLogin: '2026-08-12T16:00:00Z',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-101',
    name: 'Sheikh Khalid Al-Khalifa',
    phone: '+973 3944 1122',
    email: 'khalid.khalifa@example.bh',
    address: 'Villa 12, Riffa Views, Bahrain',
    preferredContact: 'WhatsApp',
    notes: 'Prefers ultra-soft Super 180s wool. Likes Saudi collar with double cuffs.',
    createdAt: '2026-05-10T10:00:00Z',
    updatedAt: '2026-08-01T11:30:00Z',
  },
  {
    id: 'cust-102',
    name: 'Faisal Al-Zayani',
    phone: '+973 3611 8899',
    email: 'faisal.zayani@example.com',
    address: 'Road 3405, Saar, Kingdom of Bahrain',
    preferredContact: 'Phone',
    notes: 'Regular customer for everyday Japanese Toyobo thobes.',
    createdAt: '2026-06-12T14:20:00Z',
    updatedAt: '2026-07-25T16:10:00Z',
  },
  {
    id: 'cust-103',
    name: 'Mohammed Jasim',
    phone: '+973 3322 5544',
    email: 'm.jasim@example.bh',
    address: 'Block 318, Hoora, Manama',
    preferredContact: 'WhatsApp',
    notes: 'Requests extra slim fit thobes and hidden pocket.',
    createdAt: '2026-07-01T09:15:00Z',
    updatedAt: '2026-08-05T12:00:00Z',
  },
];

export const INITIAL_MEASUREMENTS: MeasurementProfile[] = [
  {
    id: 'meas-101-v2',
    customerId: 'cust-101',
    version: 2,
    effectiveDate: '2026-08-01',
    createdBy: 'Tariq Al-Mansoor',
    neck: 16.5,
    chest: 44.0,
    waist: 38.5,
    hips: 45.0,
    shoulder: 18.5,
    sleeveLength: 34.0,
    thobeLength: 58.5,
    armhole: 21.0,
    cuff: 9.5,
    inseam: 31.0,
    fitPreference: 'Regular',
    collarStyle: 'Traditional Saudi',
    pocketStyle: 'Double Pocket',
    notes: 'Updated shoulder width by 0.5 inches after last fitting.',
  },
  {
    id: 'meas-101-v1',
    customerId: 'cust-101',
    version: 1,
    effectiveDate: '2026-05-10',
    createdBy: 'Yousef Hassan',
    neck: 16.5,
    chest: 44.0,
    waist: 39.0,
    hips: 45.0,
    shoulder: 18.0,
    sleeveLength: 34.0,
    thobeLength: 58.0,
    armhole: 20.5,
    cuff: 9.5,
    inseam: 31.0,
    fitPreference: 'Regular',
    collarStyle: 'Traditional Saudi',
    pocketStyle: 'Double Pocket',
    notes: 'Initial fitting record.',
  },
  {
    id: 'meas-102-v1',
    customerId: 'cust-102',
    version: 1,
    effectiveDate: '2026-06-12',
    createdBy: 'Yousef Hassan',
    neck: 15.5,
    chest: 40.0,
    waist: 34.0,
    hips: 41.0,
    shoulder: 17.5,
    sleeveLength: 33.0,
    thobeLength: 56.0,
    armhole: 19.5,
    cuff: 9.0,
    inseam: 29.5,
    fitPreference: 'Slim',
    collarStyle: 'Emirati Soft',
    pocketStyle: 'Single Chest',
    notes: 'Prefers soft collar without heavy stiffening.',
  },
  {
    id: 'meas-103-v1',
    customerId: 'cust-103',
    version: 1,
    effectiveDate: '2026-07-01',
    createdBy: 'Rashid Khan (Master Tailor)',
    neck: 16.0,
    chest: 42.0,
    waist: 36.0,
    hips: 43.0,
    shoulder: 18.0,
    sleeveLength: 33.5,
    thobeLength: 57.0,
    armhole: 20.0,
    cuff: 9.0,
    inseam: 30.0,
    fitPreference: 'Slim',
    collarStyle: 'Kuwaiti Mandarin',
    pocketStyle: 'Hidden Pocket',
    notes: 'Added secret phone pocket inside right seam.',
  },
];

export const INITIAL_PRODUCTS: ProductOrService[] = [
  {
    id: 'prod-1',
    name: 'Custom Royal Thobe (Bespoke Stitching)',
    category: 'Custom Tailoring',
    unitPrice: 35.000,
    defaultFabricMeters: 3.5,
    active: true,
  },
  {
    id: 'prod-2',
    name: 'Emirati Style Cotton Thobe',
    category: 'Custom Tailoring',
    unitPrice: 28.000,
    defaultFabricMeters: 3.5,
    active: true,
  },
  {
    id: 'prod-3',
    name: 'Formal Tuxedo Suit (2-Piece Custom)',
    category: 'Custom Tailoring',
    unitPrice: 120.000,
    defaultFabricMeters: 4.2,
    active: true,
  },
  {
    id: 'prod-4',
    name: 'Toyobo Royal Cotton Fabric Roll (per Meter)',
    category: 'Fabric Roll',
    unitPrice: 8.500,
    defaultFabricMeters: 1.0,
    active: true,
  },
  {
    id: 'prod-5',
    name: 'Loro Piana Italian Wool (per Meter)',
    category: 'Fabric Roll',
    unitPrice: 25.000,
    defaultFabricMeters: 1.0,
    active: true,
  },
  {
    id: 'prod-6',
    name: 'Express Alteration & Hemming',
    category: 'Alteration',
    unitPrice: 5.000,
    defaultFabricMeters: 0.0,
    active: true,
  },
  {
    id: 'prod-7',
    name: 'Luxury Brass Cufflinks Pair',
    category: 'Accessories',
    unitPrice: 15.000,
    defaultFabricMeters: 0.0,
    active: true,
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-1',
    name: 'Toyobo Japanese Royal Cotton (White)',
    code: 'FAB-TOYO-01',
    category: 'Fabric',
    color: 'Pure White',
    widthInches: 58,
    quantity: 145.0,
    unit: 'Meters',
    minThreshold: 30.0,
    costPerUnit: 4.200,
    active: true,
  },
  {
    id: 'inv-2',
    name: 'Toyobo Cotton-Linen Blend (Cream / Off-White)',
    code: 'FAB-TOYO-02',
    category: 'Fabric',
    color: 'Off-White Cream',
    widthInches: 58,
    quantity: 82.5,
    unit: 'Meters',
    minThreshold: 25.0,
    costPerUnit: 4.800,
    active: true,
  },
  {
    id: 'inv-3',
    name: 'Loro Piana Super 180s Italian Wool (Navy)',
    code: 'FAB-LP-NAVY',
    category: 'Fabric',
    color: 'Midnight Navy',
    widthInches: 60,
    quantity: 18.0, // Low stock!
    unit: 'Meters',
    minThreshold: 20.0,
    costPerUnit: 14.500,
    active: true,
  },
  {
    id: 'inv-4',
    name: 'Premium German Interlining Collar Stiffener',
    code: 'MAT-STIFF-01',
    category: 'Lining',
    color: 'White',
    widthInches: 36,
    quantity: 120.0,
    unit: 'Meters',
    minThreshold: 15.0,
    costPerUnit: 1.100,
    active: true,
  },
  {
    id: 'inv-5',
    name: 'Custom Engraved Shell Buttons (Set of 10)',
    code: 'ACC-BTN-SHELL',
    category: 'Buttons',
    color: 'Natural Mother of Pearl',
    quantity: 350,
    unit: 'Pieces',
    minThreshold: 50,
    costPerUnit: 0.350,
    active: true,
  },
];

export const INITIAL_STAFF: StaffMember[] = [
  {
    id: 'stf-1',
    name: 'Rashid Khan',
    jobTitle: 'Master Cutter & Lead Tailor',
    phone: '+973 3901 9922',
    baseSalary: 450.000,
    commissionPerPiece: 3.500,
    status: 'active',
    joinedDate: '2024-02-15',
  },
  {
    id: 'stf-2',
    name: 'Ibrahim Al-Sayed',
    jobTitle: 'Stitching Specialist (Thobes)',
    phone: '+973 3811 0033',
    baseSalary: 350.000,
    commissionPerPiece: 2.500,
    status: 'active',
    joinedDate: '2024-06-01',
  },
  {
    id: 'stf-3',
    name: 'Yousef Hassan',
    jobTitle: 'Counter Sales & POS Representative',
    phone: '+973 3655 4411',
    baseSalary: 320.000,
    commissionPerPiece: 0.000,
    status: 'active',
    joinedDate: '2025-01-10',
  },
  {
    id: 'stf-4',
    name: 'Bilal Ahmad',
    jobTitle: 'Inventory & Store Manager',
    phone: '+973 3400 7788',
    baseSalary: 380.000,
    commissionPerPiece: 0.000,
    status: 'active',
    joinedDate: '2025-03-01',
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  { id: 'att-1', staffId: 'stf-1', staffName: 'Rashid Khan', date: '2026-08-10', status: 'Present', createdBy: 'Fatima Al-Baharna' },
  { id: 'att-2', staffId: 'stf-1', staffName: 'Rashid Khan', date: '2026-08-11', status: 'Present', createdBy: 'Fatima Al-Baharna' },
  { id: 'att-3', staffId: 'stf-1', staffName: 'Rashid Khan', date: '2026-08-12', status: 'Present', createdBy: 'Fatima Al-Baharna' },
  { id: 'att-4', staffId: 'stf-2', staffName: 'Ibrahim Al-Sayed', date: '2026-08-10', status: 'Present', createdBy: 'Fatima Al-Baharna' },
  { id: 'att-5', staffId: 'stf-2', staffName: 'Ibrahim Al-Sayed', date: '2026-08-11', status: 'Half Day', notes: 'Permission for doctor visit', createdBy: 'Fatima Al-Baharna' },
  { id: 'att-6', staffId: 'stf-2', staffName: 'Ibrahim Al-Sayed', date: '2026-08-12', status: 'Present', createdBy: 'Fatima Al-Baharna' },
  { id: 'att-7', staffId: 'stf-3', staffName: 'Yousef Hassan', date: '2026-08-10', status: 'Present', createdBy: 'Fatima Al-Baharna' },
  { id: 'att-8', staffId: 'stf-3', staffName: 'Yousef Hassan', date: '2026-08-11', status: 'Present', createdBy: 'Fatima Al-Baharna' },
  { id: 'att-9', staffId: 'stf-3', staffName: 'Yousef Hassan', date: '2026-08-12', status: 'Present', createdBy: 'Fatima Al-Baharna' },
];

export const INITIAL_PERFORMANCE: PerformanceRecord[] = [
  { id: 'perf-1', staffId: 'stf-1', staffName: 'Rashid Khan', date: '2026-08-10', metric: 'Completed Thobes', units: 4, commissionEarned: 14.000, notes: 'Royal Custom Thobes' },
  { id: 'perf-2', staffId: 'stf-1', staffName: 'Rashid Khan', date: '2026-08-11', metric: 'Completed Thobes', units: 5, commissionEarned: 17.500, notes: 'Toyobo White Thobes' },
  { id: 'perf-3', staffId: 'stf-2', staffName: 'Ibrahim Al-Sayed', date: '2026-08-10', metric: 'Stitching Units', units: 3, commissionEarned: 7.500 },
  { id: 'perf-4', staffId: 'stf-2', staffName: 'Ibrahim Al-Sayed', date: '2026-08-12', metric: 'Stitching Units', units: 4, commissionEarned: 10.000 },
];

export const INITIAL_PAYOUTS: SalaryPayout[] = [
  {
    id: 'pay-2026-07-stf1',
    staffId: 'stf-1',
    staffName: 'Rashid Khan',
    payPeriod: '2026-07',
    baseSalary: 450.000,
    performanceBonus: 87.500,
    deductions: 0.000,
    netSalary: 537.500,
    status: 'Paid',
    payoutDate: '2026-07-31',
    notes: 'July 2026 salary payout completed via bank transfer.',
    approvedBy: 'Fatima Al-Baharna',
  },
  {
    id: 'pay-2026-07-stf2',
    staffId: 'stf-2',
    staffName: 'Ibrahim Al-Sayed',
    payPeriod: '2026-07',
    baseSalary: 350.000,
    performanceBonus: 45.000,
    deductions: 10.000,
    netSalary: 385.000,
    status: 'Paid',
    payoutDate: '2026-07-31',
    notes: 'Deducted BHD 10.000 advance taken on July 15.',
    approvedBy: 'Fatima Al-Baharna',
  },
];

export const INITIAL_SALES: Sale[] = [
  {
    id: 'sale-1001',
    localId: 'loc-1001',
    transactionNumber: 'TXN-2026-0041',
    customerId: 'cust-101',
    customerName: 'Sheikh Khalid Al-Khalifa',
    customerPhone: '+973 3944 1122',
    items: [
      {
        productId: 'prod-1',
        name: 'Custom Royal Thobe (Bespoke Stitching)',
        quantity: 2,
        unitPrice: 35.000,
        total: 70.000,
        measurementProfileId: 'meas-101-v2',
        assignedTailorId: 'stf-1',
        assignedTailorName: 'Rashid Khan',
        fabricId: 'inv-1',
        fabricName: 'Toyobo Japanese Royal Cotton (White)',
        fabricMetersUsed: 7.0,
      },
      {
        productId: 'prod-7',
        name: 'Luxury Brass Cufflinks Pair',
        quantity: 1,
        unitPrice: 15.000,
        total: 15.000,
      },
    ],
    subtotal: 85.000,
    discount: 5.000,
    total: 80.000,
    paymentStatus: 'Paid',
    paymentMethod: 'BenefitPay Card',
    staffUserId: 'usr-2',
    staffUserName: 'Yousef Hassan',
    timestamp: '2026-08-12T14:30:00Z',
    syncStatus: 'synced',
    offline: false,
    notes: 'Customer requested delivery within 5 business days.',
  },
  {
    id: 'sale-1002',
    localId: 'loc-1002',
    transactionNumber: 'TXN-2026-0042',
    customerId: 'cust-102',
    customerName: 'Faisal Al-Zayani',
    customerPhone: '+973 3611 8899',
    items: [
      {
        productId: 'prod-2',
        name: 'Emirati Style Cotton Thobe',
        quantity: 1,
        unitPrice: 28.000,
        total: 28.000,
        measurementProfileId: 'meas-102-v1',
        assignedTailorId: 'stf-2',
        assignedTailorName: 'Ibrahim Al-Sayed',
        fabricId: 'inv-2',
        fabricName: 'Toyobo Cotton-Linen Blend (Cream)',
        fabricMetersUsed: 3.5,
      },
    ],
    subtotal: 28.000,
    discount: 0.000,
    total: 28.000,
    paymentStatus: 'Paid',
    paymentMethod: 'Cash',
    staffUserId: 'usr-2',
    staffUserName: 'Yousef Hassan',
    timestamp: '2026-08-13T08:15:00Z',
    syncStatus: 'synced',
    offline: false,
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-doc-1001',
    invoiceNumber: 'INV-2026-0041',
    saleId: 'sale-1001',
    transactionNumber: 'TXN-2026-0041',
    customerId: 'cust-101',
    customerName: 'Sheikh Khalid Al-Khalifa',
    customerPhone: '+973 3944 1122',
    customerAddress: 'Villa 12, Riffa Views, Bahrain',
    items: INITIAL_SALES[0].items,
    subtotal: 85.000,
    discount: 5.000,
    total: 80.000,
    paymentStatus: 'Paid',
    paymentMethod: 'BenefitPay Card',
    issuedDate: '2026-08-12',
    dueDate: '2026-08-12',
    deliveryMetadata: {
      sentViaWhatsApp: true,
      sentViaEmail: false,
      printedCount: 2,
      lastActionDate: '2026-08-12T14:35:00Z',
    },
  },
  {
    id: 'inv-doc-1002',
    invoiceNumber: 'INV-2026-0042',
    saleId: 'sale-1002',
    transactionNumber: 'TXN-2026-0042',
    customerId: 'cust-102',
    customerName: 'Faisal Al-Zayani',
    customerPhone: '+973 3611 8899',
    customerAddress: 'Road 3405, Saar, Kingdom of Bahrain',
    items: INITIAL_SALES[1].items,
    subtotal: 28.000,
    discount: 0.000,
    total: 28.000,
    paymentStatus: 'Paid',
    paymentMethod: 'Cash',
    issuedDate: '2026-08-13',
    dueDate: '2026-08-13',
    deliveryMetadata: {
      sentViaWhatsApp: false,
      sentViaEmail: false,
      printedCount: 1,
      lastActionDate: '2026-08-13T08:16:00Z',
    },
  },
];

export const INITIAL_AUDIT_LOGS: AuditEvent[] = [
  {
    id: 'aud-1',
    actor: 'Tariq Al-Mansoor',
    actorRole: 'admin',
    action: 'SYSTEM_INITIALIZED',
    entity: 'ShopSettings',
    entityId: 'CR-104829-BH',
    timestamp: '2026-08-10T08:00:00Z',
    metadata: 'Initialized ERP database seed for Al-Mamlaka Haute Couture.',
  },
  {
    id: 'aud-2',
    actor: 'Yousef Hassan',
    actorRole: 'sales',
    action: 'SALE_CREATED',
    entity: 'Sale',
    entityId: 'TXN-2026-0041',
    timestamp: '2026-08-12T14:30:00Z',
    metadata: 'Completed sale for Sheikh Khalid Al-Khalifa (Total BHD 80.000 via BenefitPay Card).',
  },
  {
    id: 'aud-3',
    actor: 'Bilal Ahmad',
    actorRole: 'inventory',
    action: 'STOCK_ADJUSTMENT',
    entity: 'InventoryItem',
    entityId: 'FAB-TOYO-01',
    timestamp: '2026-08-12T15:00:00Z',
    metadata: 'Deducted 7.0 Meters for Sale TXN-2026-0041.',
  },
  {
    id: 'aud-4',
    actor: 'Fatima Al-Baharna',
    actorRole: 'payroll',
    action: 'SALARY_PAYOUT_CONFIRMED',
    entity: 'SalaryPayout',
    entityId: 'pay-2026-07-stf1',
    timestamp: '2026-07-31T16:00:00Z',
    metadata: 'Confirmed July 2026 payout BHD 537.500 to Rashid Khan.',
  },
];
