import { useAuth } from "@/_core/hooks/useAuth";
import AuthGate from "@/components/AuthGate";
import { ClipboardList, FileText, LayoutDashboard, LogOut, Package, ReceiptText, Settings, ShoppingCart, Users } from "lucide-react";
import { Link, useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Loader2, Scissors } from "lucide-react";

const navigation = [{ label: "Overview", path: "/", icon: LayoutDashboard }, { label: "Customers", path: "/customers", icon: Users }, { label: "Inventory", path: "/inventory", icon: Package }, { label: "Tailoring orders", path: "/tailoring", icon: Scissors }, { label: "Point of Sale", path: "/sales", icon: ShoppingCart }, { label: "Sales history", path: "/sales-history", icon: ReceiptText }, { label: "Invoices", path: "/invoices", icon: FileText }, { label: "Staff & Payroll", path: "/team", icon: Users }, { label: "Shop Settings", path: "/settings", icon: Settings }, { label: "Audit Trail", path: "/audit", icon: ClipboardList }];
export default function DashboardLayout({ children }: { children: React.ReactNode }) { const { user, loading, isAuthenticated, logout } = useAuth(); const [location] = useLocation(); if (loading) return <div className="flex min-h-screen items-center justify-center"><Loader2 className="animate-spin text-primary" /></div>; if (!isAuthenticated) return <AuthGate />; return <div className="min-h-screen bg-stone-50"><aside className="fixed inset-y-0 hidden w-64 border-r bg-white p-4 lg:block"><div className="flex items-center gap-3 px-3 py-4"><div className="rounded-xl bg-primary p-2 text-primary-foreground"><Scissors className="h-5 w-5" /></div><div><p className="font-semibold">Al-Mamlaka</p><p className="text-xs text-muted-foreground">Tailor ERP</p></div></div><nav className="mt-6 space-y-1">{navigation.map(item => { const Icon = item.icon; const active = location === item.path; return <Link key={item.path} href={item.path} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium ${active ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`}><Icon className="h-4 w-4" />{item.label}</Link>; })}</nav><div className="absolute inset-x-4 bottom-4 rounded-xl bg-muted p-3"><p className="truncate text-sm font-semibold">{user?.name || "Signed-in user"}</p><Button variant="ghost" size="sm" className="mt-2 w-full justify-start" onClick={() => logout()}><LogOut className="mr-2 h-4 w-4" />Sign out</Button></div></aside><header className="border-b bg-white px-5 py-4 lg:ml-64"><div className="mx-auto flex max-w-7xl items-center gap-3"><Scissors className="h-5 w-5 text-primary lg:hidden" /><p className="font-semibold lg:hidden">Al-Mamlaka ERP</p><p className="ml-auto text-sm text-muted-foreground">Secure business workspace</p></div></header><main className="p-5 lg:ml-64 lg:p-8">{children}</main></div>; }
